#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12
# Production values are recorded in .env.coolify (gitignored) — the live
# copy of every value lives in the Coolify panel, not in the dev .env.
ENV_FILE=".env.coolify"

banner "Deploy deplacementapp to production (Coolify)"

# ── Stage 1 — domain + DNS ────────────────────────────────────────────────
stage "Domain & DNS"
say "The app will be served from one domain, the Coolify panel from another."
ask APP_DOMAIN "App domain (e.g. app.example.ma):"
ask PANEL_DOMAIN "Coolify panel domain (leave empty to use the VPS IP):"
ask VPS_IP "VPS public IP address:"
say "Open your DNS provider's dashboard (registrar, Cloudflare, OVH…):"
step "Create an A record for the app host → $VPS_IP (for $APP_DOMAIN)."
if [[ -n "$PANEL_DOMAIN" ]]; then
  step "Create an A record for 'coolify' → $VPS_IP (for $PANEL_DOMAIN)."
fi
note "If the app lives at a subdomain (e.g. app.example.ma), the A record host is that subdomain."
pause "DNS records created and propagated? (dig +short $APP_DOMAIN should print $VPS_IP)"
write_env APP_DOMAIN "$APP_DOMAIN"
write_env PANEL_DOMAIN "$PANEL_DOMAIN"

# ── Stage 2 — install Coolify on the VPS ─────────────────────────────────
stage "Install Coolify on the VPS"
say "SSH into the server and run the official installer:"
open_url "https://coolify.io/docs/get-started/installation"
step "ssh root@$VPS_IP  (or your user; needs sudo)"
step "curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash"
if [[ -n "$PANEL_DOMAIN" ]]; then
  step "If the installer asks for the instance domain, enter https://$PANEL_DOMAIN"
fi
step "Open the firewall: ufw allow 22/tcp && ufw allow 80/tcp && ufw allow 443/tcp"
note "Cloud-firewall users: open ports 22, 80 and 443 in the provider dashboard instead."
note "Installation takes a few minutes; the panel URL is printed at the end."
ask COOLIFY_PANEL_URL "Coolify panel URL (printed at the end of the install):"
write_env COOLIFY_PANEL_URL "$COOLIFY_PANEL_URL"

# ── Stage 3 — first login ─────────────────────────────────────────────────
stage "First login to the Coolify panel"
open_url "${COOLIFY_PANEL_URL:-http://$VPS_IP:8000}"
step "Create the root account (name, email, password)."
warn "These are your only panel credentials — the wizard does not store them. Save them in your password manager."
pause "Root account created and you can see the dashboard?"

# ── Stage 4 — create the app resource from the repo ──────────────────────
stage "Create the app resource from the repo"
say "Coolify will deploy the repo's docker-compose.yaml (db + migrator + app)."
step "Dashboard → Projects → open your project (create one if needed)."
step "Click '+ New Resource' → 'Public Repository'."
step "Paste https://github.com/mustaphaelou/deplacementapp → Continue."
step "Build Pack: choose 'Docker Compose'."
step "Base Directory: /  —  Docker Compose Location: docker-compose.yaml"
step "Branch: main → Save."
note "Images are built on the server from the Dockerfile (targets migrator + runner); the first deploy takes 5–15 min."
pause "Resource created? (You're on its page, Environment Variables tab visible)"

# ── Stage 5 — environment variables ───────────────────────────────────────
stage "Environment variables (DB, auth secret, SMTP)"
say "The wizard generates the secrets; you paste everything into Coolify."
POSTGRES_USER="deplacementapp"
POSTGRES_DB="deplacementapp"
POSTGRES_PASSWORD=$(openssl rand -base64 24)
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
printf '\n  %sGenerated for you — copy these into Coolify:%s\n' "$BOLD" "$RESET"
note "  POSTGRES_USER      = $POSTGRES_USER"
note "  POSTGRES_DB        = $POSTGRES_DB"
note "  POSTGRES_PASSWORD  = $POSTGRES_PASSWORD"
note "  BETTER_AUTH_SECRET = $BETTER_AUTH_SECRET"
ask SMTP_HOST "SMTP host (e.g. smtp.example.ma):"
ask SMTP_PORT "SMTP port:"
[[ -z "$SMTP_PORT" ]] && SMTP_PORT="587"
ask SMTP_USER "SMTP user:"
ask_secret SMTP_PASS "SMTP password:"
ask SMTP_FROM "SMTP from address (default noreply@$APP_DOMAIN):"
[[ -z "$SMTP_FROM" ]] && SMTP_FROM="noreply@$APP_DOMAIN"
write_env POSTGRES_USER "$POSTGRES_USER"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env POSTGRES_DB "$POSTGRES_DB"
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
write_env SMTP_HOST "$SMTP_HOST"
write_env SMTP_PORT "$SMTP_PORT"
write_env SMTP_USER "$SMTP_USER"
write_env SMTP_PASS "$SMTP_PASS"
write_env SMTP_FROM "$SMTP_FROM"
say "Now in the Coolify panel, resource → Environment Variables:"
step "Replace the prefilled DB values (user/password/db) with the generated ones."
warn "The prefilled POSTGRES_PASSWORD (Mmmm2005.) and BETTER_AUTH_SECRET are committed defaults — never deploy with them."
step "Fill SMTP_HOST, SMTP_PORT (587), SMTP_USER, SMTP_PASS, SMTP_FROM."
step "Toggle the lock icon on POSTGRES_PASSWORD, BETTER_AUTH_SECRET, SMTP_PASS, SMTP_USER → Save."
pause "All environment variables pasted and saved in Coolify?"

# ── Stage 6 — domain ──────────────────────────────────────────────────────
stage "Domain & URL"
say "Point Coolify's proxy at the app service."
step "Resource → Configuration → General."
step "Set Domain to https://$APP_DOMAIN"
step "In Environment Variables, make sure BETTER_AUTH_URL is https://$APP_DOMAIN (set in the previous stage)."
note "SSL (Let's Encrypt) is issued automatically on the first deploy."
note "docker-compose.yaml maps 3000:3000 — the app is also reachable at http://$VPS_IP:3000; block that port in the firewall if unwanted."
pause "Domain set and saved?"

# ── Stage 7 — Google OAuth ────────────────────────────────────────────────
stage "Google OAuth credentials"
say "Create the OAuth client that powers 'Sign in with Google'."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create or select a project; configure the OAuth consent screen (External)."
step "Credentials → '+ Create credentials' → 'OAuth client ID' → 'Web application'."
step "Authorized redirect URIs → 'Add URI' → https://$APP_DOMAIN/api/auth/callback/google → Create."
step "Copy the Client ID and Client secret from the dialog."
ask AUTH_GOOGLE_ID "Google Client ID:"
ask_secret AUTH_GOOGLE_SECRET "Google Client secret:"
write_env AUTH_GOOGLE_ID "$AUTH_GOOGLE_ID"
write_env AUTH_GOOGLE_SECRET "$AUTH_GOOGLE_SECRET"
say "Paste both into Coolify → Environment Variables (AUTH_GOOGLE_ID, AUTH_GOOGLE_SECRET — lock the secret) → Save."
pause "Google credentials pasted and saved?"

# ── Stage 8 — first deploy ────────────────────────────────────────────────
stage "First deploy"
open_url "${COOLIFY_PANEL_URL:-http://$VPS_IP:8000}"
step "Open the resource → 'Deploy'."
step "Watch the logs: db becomes healthy → migrate runs → app starts."
step "Then open https://$APP_DOMAIN — you should see the login page."
note "First visit shows the in-app setup wizard (amorçage): create the Societé, Départements, and the admin Utilisateur."
note "If the deployment shows unhealthy, the one-shot migrate service is usually the cause — add 'exclude_from_hc: true' to it in docker-compose.yaml."
note "If pages open with localhost links, BETTER_AUTH_URL was not saved."
confirm "Is https://$APP_DOMAIN showing the login/setup page?" || {
  warn "Fix the deploy before continuing (logs: resource → Deployments)."
  pause "Press Enter when the app is reachable."
}

# ── Stage 9 — API token → GitHub secret ───────────────────────────────────
stage "Coolify API token → GitHub secret"
say "CI authenticates deploy requests with an API token."
open_url "${COOLIFY_PANEL_URL:-http://$VPS_IP:8000}"
step "Bottom-left → Settings → 'API Tokens'."
step "Generate a token (e.g. 'github-actions') — it is shown only once, copy it."
ask_secret COOLIFY_TOKEN "Paste the API token:"
set_secret COOLIFY_TOKEN "$COOLIFY_TOKEN"

# ── Stage 10 — deploy webhook → GitHub secret ─────────────────────────────
stage "Deploy webhook → GitHub secret"
say "The webhook URL lets GitHub Actions trigger a deploy."
step "Resource → Configuration → 'Webhook' section."
step "Copy the 'Deploy Webhook URL' (long URL with a uuid)."
ask_secret COOLIFY_WEBHOOK "Paste the deploy webhook URL:"
set_secret COOLIFY_WEBHOOK "$COOLIFY_WEBHOOK"

# ── Stage 11 — end-to-end webhook test ────────────────────────────────────
stage "End-to-end webhook test"
say "Verify the exact request the CI pipeline will send:"
note "  curl --request GET \"\$COOLIFY_WEBHOOK\" --header \"Authorization: Bearer \$COOLIFY_TOKEN\""
if confirm "Fire the deploy webhook now (triggers a real redeploy)?"; then
  COOLIFY_WEBHOOK="$COOLIFY_WEBHOOK" COOLIFY_TOKEN="$COOLIFY_TOKEN" \
    bash scripts/deploy-coolify.sh --ref webhook-test
  pause "Watch the deployment on the resource page, then press Enter."
else
  note "Skipped — the same request fires automatically when a release tag is pushed."
fi

# ── Stage 12 — release tag (CI deploy) ────────────────────────────────────
stage "Release tag (CI deploy)"
say "Pushing a vX.Y.Z tag runs the pipeline: lint/typecheck/tests → smoke test →"
say "multi-arch image build → GitHub Release draft → deploy job fires the webhook."
if confirm "Create and push a release tag now (triggers a production deploy)?"; then
  ask TAG "Tag name (default v0.1.0):"
  [[ -z "$TAG" ]] && TAG="v0.1.0"
  git tag "$TAG"
  git push origin "$TAG"
  open_url "https://github.com/mustaphaelou/deplacementapp/actions"
  pause "Watch the pipeline; the deploy job fires the webhook at the end."
else
  note "Skipped — push a tag later: git tag v0.1.0 && git push origin v0.1.0"
fi

finish
